<?php
require_once 'includes/config.php';
require_once 'includes/functions.php';

requireLogin();

// Get summary ID and format
$summary_id = isset($_GET['summary_id']) ? intval($_GET['summary_id']) : 0;
$format = isset($_GET['format']) ? $_GET['format'] : 'txt';

// Validate format
if (!in_array($format, ['pdf', 'txt', 'docx'])) {
    die('Invalid export format');
}

// Fetch summary with paper details
$stmt = $conn->prepare("
    SELECT s.*, p.title as paper_title, p.authors 
    FROM summaries s 
    JOIN papers p ON s.paper_id = p.id 
    WHERE s.id = ? AND s.user_id = ?
");
$stmt->bind_param("ii", $summary_id, $_SESSION['user_id']);
$stmt->execute();
$result = $stmt->get_result();
$summary = $result->fetch_assoc();
$stmt->close();

if (!$summary) {
    die('Summary not found or you do not have permission to export it.');
}

// Export based on format
switch ($format) {
    case 'txt':
        exportTXT($summary);
        break;
    case 'pdf':
        exportPDF($summary);
        break;
    case 'docx':
        exportDOCX($summary);
        break;
}

/**
 * Export summary as plain text file
 */
function exportTXT($summary) {
    $filename = generateFilename($summary, 'txt');
    
    $content = "RESEARCH PAPER SUMMARY\n";
    $content .= str_repeat("=", 80) . "\n\n";
    $content .= "Title: " . $summary['paper_title'] . "\n";
    if ($summary['authors']) {
        $content .= "Authors: " . $summary['authors'] . "\n";
    }
    $content .= "Summary Type: " . ucfirst($summary['summary_type']) . "\n";
    $content .= "Generated: " . date('F d, Y', strtotime($summary['created_at'])) . "\n";
    $content .= "Word Count: " . $summary['word_count'] . "\n";
    $content .= "AI Model: " . $summary['ai_model_used'] . "\n";
    $content .= "\n" . str_repeat("=", 80) . "\n\n";
    $content .= "SUMMARY\n";
    $content .= str_repeat("-", 80) . "\n\n";
    $content .= wordwrap($summary['content'], 80) . "\n\n";
    $content .= str_repeat("=", 80) . "\n";
    $content .= "Generated by PaperVista - AI Academic Paper Summarizer\n";
    $content .= "© 2025 University Of Technology And Applied Science\n";
    
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($content));
    echo $content;
    exit;
}

/**
 * Export summary as PDF using TCPDF
 */
function exportPDF($summary) {
    try {
        // Load TCPDF library
        require_once __DIR__ . '/vendor/autoload.php';
        
        // Create PDF object with proper parameters
        $pdf = new \TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
        
        // Set document information
        $pdf->SetCreator('PaperVista');
        $pdf->SetAuthor('PaperVista - AI Academic Paper Summarizer');
        $pdf->SetTitle('Summary - ' . $summary['paper_title']);
        $pdf->SetSubject('Research Paper Summary');
        
        // Set default monospaced font
        $pdf->SetDefaultMonospacedFont('courier');
        
        // Set margins
        $pdf->SetMargins(15, 15, 15);
        $pdf->SetAutoPageBreak(TRUE, 15);
        
        // Add page
        $pdf->AddPage();
        
        // Set font
        $pdf->SetFont('helvetica', 'B', 20);
        $pdf->SetTextColor(30, 64, 175); // Blue color
        
        // Title
        $pdf->Cell(0, 10, 'Research Paper Summary', 0, 1, 'C');
        
        // Line break
        $pdf->SetDrawColor(30, 64, 175);
        $pdf->Line(15, $pdf->GetY() + 2, 195, $pdf->GetY() + 2);
        $pdf->Ln(8);
        
        // Metadata section
        $pdf->SetFont('helvetica', '', 11);
        $pdf->SetTextColor(0, 0, 0);
        
        // Paper title
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(40, 7, 'Title:', 0, 0);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->MultiCell(0, 7, wordwrap($summary['paper_title'], 85), 0, 'L');
        
        // Authors
        if ($summary['authors']) {
            $pdf->SetFont('helvetica', 'B', 11);
            $pdf->Cell(40, 7, 'Authors:', 0, 0);
            $pdf->SetFont('helvetica', '', 11);
            $pdf->MultiCell(0, 7, wordwrap($summary['authors'], 85), 0, 'L');
        }
        
        // Summary type
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(40, 7, 'Summary Type:', 0, 0);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->Cell(0, 7, ucfirst($summary['summary_type']), 0, 1);
        
        // Generated date
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(40, 7, 'Generated:', 0, 0);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->Cell(0, 7, date('F d, Y', strtotime($summary['created_at'])), 0, 1);
        
        // Word count
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(40, 7, 'Word Count:', 0, 0);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->Cell(0, 7, number_format($summary['word_count']) . ' words', 0, 1);
        
        // AI Model
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->Cell(40, 7, 'AI Model:', 0, 0);
        $pdf->SetFont('helvetica', '', 11);
        $pdf->Cell(0, 7, $summary['ai_model_used'], 0, 1);
        
        // Summary content section
        $pdf->Ln(5);
        $pdf->SetDrawColor(200, 200, 200);
        $pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
        $pdf->Ln(5);
        
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->SetTextColor(30, 64, 175);
        $pdf->Cell(0, 10, 'SUMMARY', 0, 1);
        
        $pdf->SetFont('helvetica', '', 11);
        $pdf->SetTextColor(0, 0, 0);
        
        // Summary content with justified alignment
        $pdf->MultiCell(0, 6, $summary['content'], 0, 'J');
        
        // Footer
        $pdf->Ln(10);
        $pdf->SetDrawColor(200, 200, 200);
        $pdf->Line(15, $pdf->GetY(), 195, $pdf->GetY());
        $pdf->Ln(5);
        
        $pdf->SetFont('helvetica', 'I', 10);
        $pdf->SetTextColor(100, 100, 100);
        $pdf->Cell(0, 5, 'Generated by PaperVista - AI Academic Paper Summarizer', 0, 1, 'C');
        $pdf->Cell(0, 5, '© 2025 University Of Technology And Applied Science', 0, 1, 'C');
        
        // Generate filename
        $filename = generateFilename($summary, 'pdf');
        
        // Output PDF as download
        $pdf->Output($filename, 'D');
        exit;
        
    } catch (Exception $e) {
        die('Error generating PDF: ' . $e->getMessage());
    }
}

/**
 * Export summary as DOCX
 * This creates a simple DOCX file structure
 */
function exportDOCX($summary) {
    $filename = generateFilename($summary, 'docx');
    
    // Create DOCX XML content
    $content = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
    <w:body>
        <w:p>
            <w:pPr><w:jc w:val="center"/></w:pPr>
            <w:r>
                <w:rPr><w:b/><w:sz w:val="32"/></w:rPr>
                <w:t>RESEARCH PAPER SUMMARY</w:t>
            </w:r>
        </w:p>
        <w:p><w:r><w:t></w:t></w:r></w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Title: </w:t></w:r>
            <w:r><w:t>' . htmlspecialchars($summary['paper_title']) . '</w:t></w:r>
        </w:p>';
    
    if ($summary['authors']) {
        $content .= '<w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Authors: </w:t></w:r>
            <w:r><w:t>' . htmlspecialchars($summary['authors']) . '</w:t></w:r>
        </w:p>';
    }
    
    $content .= '
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Summary Type: </w:t></w:r>
            <w:r><w:t>' . ucfirst($summary['summary_type']) . '</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Generated: </w:t></w:r>
            <w:r><w:t>' . date('F d, Y', strtotime($summary['created_at'])) . '</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t>Word Count: </w:t></w:r>
            <w:r><w:t>' . $summary['word_count'] . '</w:t></w:r>
        </w:p>
        <w:p><w:r><w:t></w:t></w:r></w:p>
        <w:p>
            <w:pPr><w:jc w:val="both"/></w:pPr>';
    
    // Split content into paragraphs
    $paragraphs = explode("\n\n", $summary['content']);
    foreach ($paragraphs as $para) {
        $para = trim($para);
        if (!empty($para)) {
            $content .= '<w:r><w:t xml:space="preserve">' . htmlspecialchars($para) . '</w:t></w:r>';
        }
        $content .= '</w:p><w:p><w:pPr><w:jc w:val="both"/></w:pPr>';
    }
    
    $content .= '
        </w:p>
        <w:p><w:r><w:t></w:t></w:r></w:p>
        <w:p>
            <w:pPr><w:jc w:val="center"/></w:pPr>
            <w:r><w:rPr><w:i/></w:rPr><w:t>Generated by PaperVista - AI Academic Paper Summarizer</w:t></w:r>
        </w:p>
        <w:p>
            <w:pPr><w:jc w:val="center"/></w:pPr>
            <w:r><w:rPr><w:i/></w:rPr><w:t>© 2025 University Of Technology And Applied Science</w:t></w:r>
        </w:p>
    </w:body>
</w:document>';
    
    // Create temporary directory for DOCX structure
    $temp_dir = sys_get_temp_dir() . '/docx_' . uniqid();
    mkdir($temp_dir);
    mkdir($temp_dir . '/word');
    mkdir($temp_dir . '/_rels');
    mkdir($temp_dir . '/word/_rels');
    
    // Create document.xml
    file_put_contents($temp_dir . '/word/document.xml', $content);
    
    // Create [Content_Types].xml
    $content_types = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
    <Default Extension="xml" ContentType="application/xml"/>
    <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>';
    file_put_contents($temp_dir . '/[Content_Types].xml', $content_types);
    
    // Create _rels/.rels
    $rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>';
    file_put_contents($temp_dir . '/_rels/.rels', $rels);
    
    // Create ZIP archive
    $zip = new ZipArchive();
    $zip_path = sys_get_temp_dir() . '/' . $filename;
    
    if ($zip->open($zip_path, ZipArchive::CREATE) === TRUE) {
        $zip->addFile($temp_dir . '/[Content_Types].xml', '[Content_Types].xml');
        $zip->addFile($temp_dir . '/_rels/.rels', '_rels/.rels');
        $zip->addFile($temp_dir . '/word/document.xml', 'word/document.xml');
        $zip->close();
        
        // Send file to browser
        header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . filesize($zip_path));
        readfile($zip_path);
        
        // Clean up
        unlink($zip_path);
        unlink($temp_dir . '/[Content_Types].xml');
        unlink($temp_dir . '/_rels/.rels');
        unlink($temp_dir . '/word/document.xml');
        rmdir($temp_dir . '/word/_rels');
        rmdir($temp_dir . '/word');
        rmdir($temp_dir . '/_rels');
        rmdir($temp_dir);
    }
    
    exit;
}

/**
 * Generate filename for export
 */
function generateFilename($summary, $extension) {
    $title = preg_replace('/[^a-z0-9]+/i', '_', $summary['paper_title']);
    $title = substr($title, 0, 50);
    $type = $summary['summary_type'];
    return "summary_{$type}_{$title}.{$extension}";
}
?>
